from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

"""
#STUDENT HEADER TABLE#
SCHOOL_ID
STUDENT_ID = SID #PRIMARY KEY AND AUTOINCREMENT "IF ONE STUDENT IS BELEATE AND NEW STUDENT ADDED HE WILL GET NEW SID NOT DELETED ID."
STUDENT_NAME = ""
STUDENT_DOB = ""
STUDENT_TYPE = "MALE OR FEMALE OR TRANS GENDER"
STUDENT_EMAIL = ""
STUDENT_PHONE = ""
STUDENT_FATHER_NAME = ""
STUDENT_MOTHER_NAME = ""
STUDENT_ID_PASSWORD = ""
STUDENT_STATUS = "ACTIVE OR DEACTIVATED OR SUSPENDED"
CREATED_AT
UPDATED_AT
"""